# Generated by Django 5.0.6 on 2024-05-18 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_product_image_url_product_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='MyariSaponi',
        ),
    ]
