# Generated by Django 5.0.6 on 2024-05-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_rename_product_myarisaponi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tsubi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('photo', models.ImageField(blank=True, upload_to='static/img')),
            ],
        ),
    ]
