# Generated by Django 5.0.6 on 2024-05-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_chusti_dispenserebi_elitealternativee_petbotli'),
    ]

    operations = [
        migrations.CreateModel(
            name='EliteAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('photo', models.ImageField(blank=True, upload_to='gallery/static/img/EliteAlternative')),
            ],
        ),
        migrations.DeleteModel(
            name='EliteAlternativee',
        ),
        migrations.AlterField(
            model_name='chusti',
            name='photo',
            field=models.ImageField(blank=True, upload_to='gallery/static/img/Chusti'),
        ),
        migrations.AlterField(
            model_name='dispenserebi',
            name='photo',
            field=models.ImageField(blank=True, upload_to='gallery/static/img/Dispenserebi'),
        ),
        migrations.AlterField(
            model_name='myarisaponi',
            name='photo',
            field=models.ImageField(blank=True, upload_to='gallery/static/img/MyariSaponi'),
        ),
        migrations.AlterField(
            model_name='petbotli',
            name='photo',
            field=models.ImageField(blank=True, upload_to='gallery/static/img/PetBotli'),
        ),
        migrations.AlterField(
            model_name='tsubi',
            name='photo',
            field=models.ImageField(blank=True, upload_to='gallery/static/img/Tsubi'),
        ),
    ]
