# Generated by Django 5.0.6 on 2024-05-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_myarisaponi_headeren'),
    ]

    operations = [
        migrations.AddField(
            model_name='chusti',
            name='headerEn',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dispenserebi',
            name='headerEn',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='elitealternative',
            name='headerEn',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='petbotli',
            name='headerEn',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tsubi',
            name='headerEn',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
