# Generated by Django 5.0.6 on 2024-05-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_chusti_headeren_dispenserebi_headeren_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chusti',
            old_name='headerEn',
            new_name='headerEng',
        ),
        migrations.RenameField(
            model_name='dispenserebi',
            old_name='headerEn',
            new_name='headerEng',
        ),
        migrations.RenameField(
            model_name='elitealternative',
            old_name='headerEn',
            new_name='headerEng',
        ),
        migrations.RenameField(
            model_name='myarisaponi',
            old_name='headerEn',
            new_name='headerEng',
        ),
        migrations.RenameField(
            model_name='petbotli',
            old_name='headerEn',
            new_name='headerEng',
        ),
        migrations.RenameField(
            model_name='tsubi',
            old_name='headerEn',
            new_name='headerEng',
        ),
    ]
