# Generated by Django 5.0.7 on 2024-08-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_remove_chusti_price_remove_dispenserebi_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chusti',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Chusti'),
        ),
        migrations.AlterField(
            model_name='dispenserebi',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Dispenserebi'),
        ),
        migrations.AlterField(
            model_name='elitealternative',
            name='photo',
            field=models.ImageField(blank=True, upload_to='EliteAlternative'),
        ),
        migrations.AlterField(
            model_name='myarisaponi',
            name='photo',
            field=models.ImageField(blank=True, upload_to='MyariSaponi'),
        ),
        migrations.AlterField(
            model_name='petbotli',
            name='photo',
            field=models.ImageField(blank=True, upload_to='PetBotli'),
        ),
        migrations.AlterField(
            model_name='tsubi',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Tsubi'),
        ),
    ]
