# Generated by Django 5.0.7 on 2024-08-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_remove_chusti_price_remove_dispenserebi_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenitebi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('headerEng', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='Amenitebi')),
            ],
        ),
        migrations.CreateModel(
            name='Partniorebi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('headerEng', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='Partniorebi')),
            ],
        ),
        migrations.CreateModel(
            name='Saponi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('headerEng', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='Saponi')),
            ],
        ),
        migrations.CreateModel(
            name='TavisMovla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('headerEng', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='TavisMovla')),
            ],
        ),
        migrations.DeleteModel(
            name='EliteAlternative',
        ),
        migrations.DeleteModel(
            name='MyariSaponi',
        ),
        migrations.DeleteModel(
            name='PetBotli',
        ),
        migrations.DeleteModel(
            name='Tsubi',
        ),
        migrations.AlterField(
            model_name='chusti',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Chusti'),
        ),
        migrations.AlterField(
            model_name='dispenserebi',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Dispenserebi'),
        ),
    ]
